config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'books#index'
    get 'books' => 'books#index'
    get 'books/new'  =>  'books#new'
    post  'books'      =>  'books#create'
    get 'books/search' => 'books#search'
    get 'books/:id' => 'books#show'
    delete 'books/:id' => 'books#destroy'
    get 'books/edit/:id' => 'books#edit'
    patch 'books/:id' => 'books#update'
    get 'users/:id' => 'users#show'
    get 'users/:id/reviews' => 'users#show_reviews'
  resources :reviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/module/_header-mypage.html.erb
              <header class="header">
                <div class="user-sign_in">
                  <% if user_signed_in? %>
                  <div class="login_user_link">
                    <%= link_to root_path, class: "menu_link" do %>
                    <i class="fas fa-home"></i>
                    <% end %>
                    <div class=search_form>
                      <%= form_with(model: @book, url: books_search_path, method: :get, local: true) do |f| %>
                      <%= f.text_field :keyword, class: 'form__message', placeholder: ''%>
                      <%= button_tag type: "submit", name: nil, class: "search" do %>
                      <i class="fas fa-search"></i>
                      <% end %>
                      <% end %>
                    </div>
                  </div>
                  <nav>
                    <%= image_tag current_user.image.thumb50.url, class: "header_user_image" %>
                    <button class=menu_button><span>Menu</span>
                      <i class="fas fa-caret-down"></i>
                    </button>
                    <ul class=menu>
                      <%= link_to "/users/#{current_user.id}", class: "menu_link" do %>
                      <li><i class="fas fa-user"></i>マイページ</li>
                      <% end %>
                      <%= link_to "/users/#{current_user.id}/reviews", class: "menu_link" do %>
                      <li><i class="far fa-comment"></i>書評一覧</li>
                      <% end %>
                      <%= link_to edit_user_registration_path, class: "menu_link" do %>
                      <li><i class="fas fa-cog"></i>ユーザー編集</li>
                      <% end %>
                      <%= link_to destroy_user_session_path, method: :delete, class: "menu_link" do %>
                      <li class=li_last><i class="fas fa-sign-out-alt"></i>ログアウト</li>
                      <% end %>
                    </ul>
                  </nav>
                  <% else %>
                  <div class="user_link">
                    <%= link_to root_path, class: "menu_link" do %>
                    <i class="fas fa-home"></i>
                    <% end %>
                    <div class=search_form>
                      <%= form_with(model: @book, url: books_search_path, method: :get, local: true) do |f| %>
                      <%= f.text_field :keyword, class: 'form__message', placeholder: ''%>
                      <%= button_tag type: "submit", name: nil, class: "search" do %>
                      <i class="fas fa-search"></i>
                      <% end %>
                      <% end %>
                    </div>
                    <div class=login_signup_button>
                      <%= link_to new_user_session_path, class: 'login' do %>
                      <i class="fas fa-sign-in-alt"></i><span>ログイン</span>
                      <% end %>
                      <%= link_to new_user_registration_path, class: 'registration' do %>
                      <i class="fas fa-user-plus"></i><span>新規登録</span>
                      <% end %>
                    </div>
                  </div>
                  <% end %>
                </div>
              </header>

app/views/module/_header.html.erb
              <header class="header">
                <div class="user-sign_in">
                  <% if user_signed_in? %>
                  <div class="login_user_link">
                    <%= link_to root_path, class: "menu_link" do %>
                    <i class="fas fa-home"></i>
                    <% end %>
                    <div class=search_form>
                      <%= form_with(model: @book, url: books_search_path, method: :get, local: true) do |f| %>
                      <%= f.text_field :keyword, class: 'form__message', placeholder: ''%>
                      <%= button_tag type: "submit", name: nil, class: "search" do %>
                      <i class="fas fa-search"></i>
                      <% end %>
                      <% end %>
                    </div>
                  </div>
                  <nav>
                    <%= image_tag current_user.image.thumb50.url, class: "header_user_image" %>
                    <button class=menu_button><span>Menu</span>
                      <i class="fas fa-caret-down"></i>
                    </button>
                    <ul class=menu>
                      <%= link_to "/users/#{current_user.id}", class: "menu_link" do %>
                      <li><i class="fas fa-user"></i>マイページ</li>
                      <% end %>
                      <%= link_to "/users/#{current_user.id}/reviews", class: "menu_link" do %>
                      <li><i class="far fa-comment"></i>書評一覧</li>
                      <% end %>
                      <%= link_to edit_user_registration_path, class: "menu_link" do %>
                      <li><i class="fas fa-cog"></i>ユーザー編集</li>
                      <% end %>
                      <%= link_to destroy_user_session_path, method: :delete, class: "menu_link" do %>
                      <li class=li_last><i class="fas fa-sign-out-alt"></i>ログアウト</li>
                      <% end %>
                    </ul>
                  </nav>
                  <% else %>
                  <div class="user_link">
                    <%= link_to root_path, class: "menu_link" do %>
                    <i class="fas fa-home"></i>
                    <% end %>
                    <div class=search_form>
                      <%= form_with(model: @book, url: books_search_path, method: :get, local: true) do |f| %>
                      <%= f.text_field :keyword, class: 'form__message', placeholder: ''%>
                      <%= button_tag type: "submit", name: nil, class: "search" do %>
                      <i class="fas fa-search"></i>
                      <% end %>
                      <% end %>
                    </div>
                    <div class=login_signup_button>
                      <%= link_to new_user_session_path, class: 'login' do %>
                      <i class="fas fa-sign-in-alt"></i><span>ログイン</span>
                      <% end %>
                      <%= link_to new_user_registration_path, class: 'registration' do %>
                      <i class="fas fa-user-plus"></i><span>新規登録</span>
                      <% end %>
                    </div>
                  </div>
                  <% end %>
                </div>
              </header>